# Express Gateway Lite Configuration
# This is a sample configuration file
# CLI arguments will override these settings

# Port to listen on
port: 3000

# Path to serve static files from
path: ./public

# Enable compression
compression: true

# Proxy configuration as comma-separated key=value pairs
proxy: >
  /api/users=http://user-service:8080/v2,
  /api/auth=http://auth-service:8080/oauth,
  /ui/components=http://component-service:8080/public,

# Development server settings
devServer: false
noReload: false

# Launch browser on Windows
launch: false 