# Express Gateway Lite Configuration
# This is a sample configuration file
# CLI arguments will override these settings

# Port to listen on
port: 3000

# Path to serve static files from
path: ./public

# Enable compression
compression: true

# Proxy configuration
proxy:
  /api: http://api.example.com
  /auth: http://auth.example.com

# Development server settings
devServer: false
noReload: false
